import type { Metadata } from "next";
import { getServerSession } from "next-auth"; // Import for server-side session retrieval
import { authOptions } from "./api/auth/[...nextauth]/route"; // Adjust the path as necessary
import SessionProviderWrapper from "./SessionProviderWrapper"; // // Import for server-side session retrieval
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProviderWrapper>
           {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}



