import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}



// // app/layout.tsx
// import { getServerSession } from "next-auth"; // Import for server-side session retrieval
// import { authOptions } from "./api/auth/[...nextauth]/route"; // Adjust the path as necessary
// import SessionProviderWrapper from "./SessionProviderWrapper"; // Import your custom provider

// export default async function RootLayout({ children }: { children: React.ReactNode }) {
//   const session = await getServerSession(authOptions); // Get the session on the server side

//   return (
//     <html lang="en">
//       <body>
//         <SessionProviderWrapper session={session}>
//           {children}
//         </SessionProviderWrapper>
//       </body>
//     </html>
//   );
// }
